### ISSUE TITLE
Upgrade to nom 5

### ISSUE THREAD

**Issue by james-darkfox** [rusticata/pcap-parser#1]
Are there any immediate plans to migrate to nom 5? I've found rusticata's set of parsers to be useful examples for using nom. nom 5 moves from macros to function combinators - generally improving the readability and performance at both runtime and compile time.

**Comment by chifflier** [comment]
All the parsers will be updated to nom 5
I am doing other transitions first (new DER API, rewritten PCAP) first so they can be used in, for ex, Suricata (which has to be compatible with older Rust compilers, and so for now nom 5 cannot be used). After that, I'll start upgrading parsers to nom 5

**Comment by chifflier** [comment]
Upgrade to nom 5 was done in b25a12b (and released in crate version [0.7.0](https://crates.io/crates/pcap-parser/0.7.0)), so closing this issue

**Comment by james-darkfox** [comment]
That was a less exciting upgrade. I was hoping you'd switch from the macros to the function combinators. Oh well, what works, works.

**Comment by chifflier** [comment]
Heh, I did first the API change to bump dependencies (which resulted in a lot of changes in all my parsers).
Using the function combinators is still planned, but can be done without breaking the crate API if I'm correct.

**Comment by james-darkfox** [comment]
@chifflier I believe you are correct. Good luck.
