### ISSUE TITLE
Infinite loop happens when pcap files with truncated packet

### ISSUE THREAD

**Issue by op8867555** [rusticata/pcap-parser#20]
Hi, I followed the [example](https://github.com/rusticata/pcap-parser/blob/444ccc6ccb43b30694cc352fa3b2fea9c9fb2baa/src/capture_pcap.rs#L35) and found out that a truncated packet will make the example parser stuck in an infinite loop, since:

* `PcapReaderIterator.refill()` always return `Ok` even if the reader is exhausted, and
* `PcapReaderIterator.next()` won't return EOF because there are still data available.

My current workaround is checking `reader_exhausted()` after every `refill()` calls.
~~~rust
Err(PcapError::Incomplete) => {
    reader.refill().unwrap();
    if reader.reader_exhausted() { break; }
},
~~~
Is this behavior expected or a bug?

**Comment by chifflier** [comment]
Hi,
This example was indeed incomplete, and was missing the code to handle incomplete blocks.

This is a duplicate of #18 and fixed in b4a526f3404380f63624ef862c95450a8571e6e7 (see these links for complete examples).
Closing this issue as it is now fixed.
