### ISSUE TITLE
crates.io version out of date

### ISSUE THREAD

**Issue by 0rphon** [rusticata/pcap-parser#41]
Hi! I see the github version of this crate has been on version 0.16.0 for two months now, but the crates.io version is still on 0.15.0. From the commit history, it seems like version 0.16.0 was meant to be released. So im just double checking that you guys didn't accidentally forget to publish it to crates.io.

I noticed this because version 0.16.0 includes support for `Linktype::LINUX_SLL2` in `pcap_parser::data::get_packetdata`, which is used by tcpdump. For now i just used a cargo patch to point at the github version instead, but it would be nice to have the crates.io version up to date.

**Comment by chifflier** [comment]
Hi,
You're right, the release was just ready but had not been uploaded to crates.io.
I have released `pcap-parser` 0.16.0, so closing this
Thanks
