### ISSUE TITLE
How to add fake pcap header before parsing

### ISSUE THREAD

**Issue by mhristache** [rusticata/pcap-parser#5]
Hi

I am trying to build a packet sniffer server and I am receiving pcap lib Packets via TCP but without the pcap file header. Is there a way to parse these packets using pcap-parser, e.g. add a pcap file header on the server side before calling the pcap-parser? The datalink type is always the same so that should not be an issue.

Thank you

**Comment by chifflier** [comment]
Hi,
Not sure I understand correctly. If you are receiving encapsulated packets (assuming the encapsulation is pcap, not pcap-ng), there are several options:
- you can call [`parse_pcap_frame`](https://docs.rs/pcap-parser/0.8.2/pcap_parser/pcap/fn.parse_pcap_frame.html) directly on the data, however you'll have to handle the fragmentation (if any)
- if you want to use the streaming API ( [`LegacyPcapReader`](https://docs.rs/pcap-parser/0.8.2/pcap_parser/struct.LegacyPcapReader.html) ), you'll have to create a struct providing the `Read` trait. This structure would return a forged legacy pcap header on the first call, which is not too hard to create (see [`PcapHeader`](https://docs.rs/pcap-parser/0.8.2/pcap_parser/pcap/struct.PcapHeader.html)). Most fields are fixed, but you have to know `snaplen`. `linktype` is not necessary in the header (it is only called when parsing data). If you use the `serialize` feature, you can even create the struct and serialize it.

**Comment by mhristache** [comment]
Thanks for the help! 
I got it working using the streaming API by creating a forged pcap header then chain it into the original data usin the [`Read::chain`](https://doc.rust-lang.org/std/io/trait.Read.html#method.chain) method.
